### ISSUE TITLE
The link to SyNRAC is dead; is there an archive of this (free) library?

### ISSUE THREAD

**Issue by PoeticExposition** [kovzol/realgeom#5]
As the [installation section](https://github.com/kovzol/realgeom?tab=readme-ov-file#installation) says, outsourced computations can be done via Maple in the subsystems `SyNRAC`. Unfortunately, when I click on the link to SyNRAC, I just get an error message “Page Not Found”. I have since tried searching for it on Google, but could not find any downloadable resources; the only things I could find were some articles about it, while the links provided in the articles were broken again. Now that SyNRAC is said to be "publicly available", does there exist any other way to obtain this toolbox? 
Notes. Of course, I can use something like RegularChains and Redlog (Regretfully, Tarski and QEPCAD are not ready-to-use on Windows OS), yet I noticed that SyNRAC has certain performance advantages (which are illustrated in the Figure 7-8 on page 274 of [this thesis](https://researchportal.bath.ac.uk/files/221903891/ZPT_Thesis.pdf)) over other packages.  Besides, although there appears to be a successor, [`GaNRAC`](https://github.com/hiwane/ganrac), written by the developer of SyNRAC, one of its requirements, SageMath, is not immediately available (I mean, without WSL/Cygwin/...) on Windows either…

**Comment by kovzol** [comment]
Here is a copy of the main page: https://web.archive.org/web/20190211123004/http://www.fujitsu.com/jp/group/labs/en/resources/tech/announced-tools/synrac/, but, unfortunately, the Download section seems unarchived. I'll check if I have a personal copy of Synrac somewhere.

**Comment by kovzol** [comment]
Here you can find a copy: https://matek.hu/zoltan/synrac/

**Comment by PoeticExposition** [comment]
> Here you can find a copy: https://matek.hu/zoltan/synrac/

Thanks for for getting back to me! I'll try it right away.
